<?php
/**
 * @var \Friday\Web\View $this
 * @var string $content
 */
use Friday\Bootstrap\Widget\Nav;
use Friday\Bootstrap\Widget\NavBar;
use Friday\Helper\Html;

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Friday::$app->language ?>">
<head>
    <meta charset="<?= Friday::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
    <?php $this->beginBody() ?>

    <?= NavBar::widget(['brandLabel' => 'Friday',
        'items' => [
            [
                'label' => Friday::t('app', 'Home'),
                'url' => ['/index/index'],
            ],
            [
                'label' => 'Dropdown',
                'items' => [
                    ['label' => 'Level 1 - Dropdown A', 'url' => '#'],
                    ['label' => 'Dropdown Header'],
                    null,
                    ['label' => 'Level 1 - Dropdown B', 'url' => '#'],
                ]
            ],
            [
                'label' => 'Login',
                'url' => ['site/login'],
                //'visible' => Friday::$app->user->isGuest
            ],
        ],
        'afterItems' => Html::a(Friday::t('app', 'Sign In'), '#signin',
            [
                'class' => 'btn btn-outline-success my-2 my-sm-0',
            ]
        )

    ])?>
    <?= $content ?>
    <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>