<?php
/**
 * @var \Friday\Web\View $this
 * @var string $content
 */
use Friday\Bootstrap\Widget\Nav;
use Friday\Bootstrap\Widget\NavBar;
use Friday\Helper\Html;

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Friday::$app->language ?>">
<head>
    <meta charset="<?= Friday::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
    <?php $this->beginBody() ?>

    <?php
    NavBar::begin(['brandLabel' => 'Friday',
        'items' => [
            [
                'label' => 'Home',
                'url' => ['/site/index'],
            ],
            [
                'label' => 'Dropdown',
                'items' => [
                    ['label' => 'Level 1 - Dropdown A', 'url' => '#'],
                    ['label' => 'Dropdown Header'],
                    null,
                    ['label' => 'Level 1 - Dropdown B', 'url' => '#'],
                ],
            ],
            [
                'label' => 'Login',
                'url' => ['site/login'],
                //'visible' => Friday::$app->user->isGuest
            ],
        ],
        ]);

    NavBar::end()?>
    <?= $content ?>
    <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>